[package]
name = "ai-safety-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
thiserror = "2.0.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
